server:
  port: ${PORT:8081}
  shutdown: graceful

spring:
  application:
    name: notification-service
  lifecycle:
    timeout-per-shutdown-phase: 20s

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false # We will demonstrate manual / container acknowledgment
      properties:
        spring.json.trusted.packages: "*"
        session.timeout.ms: 30000
        heartbeat.interval.ms: 3000
        max.poll.interval.ms: 300000
        max.poll.records: 50
    listener:
      ack-mode: RECORD # Commits offset immediately after successful listener execution

app:
  kafka:
    topic: orders.v1

# Spring Boot Actuator for Kubernetes Liveness & Readiness Probes
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
